### ISSUE TITLE
Policy has not been signed

### ISSUE THREAD

**Issue by kravciak** [kubewarden/container-resources-policy#15]
https://artifacthub.io/packages/kubewarden/container-resources/container-resources

![Screenshot from 2024-02-15 08-17-38](https://github.com/kubewarden/container-resources-policy/assets/538604/b748a4da-68c6-4d25-8e82-c3602a5d2d5e)

**Comment by jvanz** [comment]
It looks like an issue in the artifact hub. I've open an [issue](https://github.com/artifacthub/hub/issues/3661) there.

**Comment by jvanz** [comment]
I've double check the repository settings and seems that we missed to change the security check flag. Now the policy is marked as signed. 

![image](https://github.com/kubewarden/container-resources-policy/assets/1514798/82158cf6-0bc4-451e-9a27-7fe59f5d7b9e)

**Comment by kravciak** [comment]
Reopening the issue, after policy update it's unsigned again.

**Comment by jvanz** [comment]
After the last fixes in the artifacthub files, the policy is set as signed again:

![image](https://github.com/kubewarden/container-resources-policy/assets/1514798/80bacf17-a65e-4c59-8ebf-a2fb90e11990)
