### ISSUE TITLE
Can't create policy by filling only CPU settings

### ISSUE THREAD

**Issue by kravciak** [kubewarden/container-resources-policy#33]
### Current Behavior

I create new policy container-resources:v0.2.3 in kubewarden UI and provide only CPU settings.
Policy fails with following error:

```
libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE
libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE
libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE
2024-04-19T06:30:26.246868Z  INFO validate_settings{self=PolicyEvaluator { runtime: "wapc" } settings={"cpu": Object {"defaultLimit": String("200m"), "defaultRequest": String("100m"), "ignoreValues": Bool(false), "maxLimit": String("300m")}, "memory": Object {"ignoreValues": Bool(false)}}}:policy_log{self=EvaluationContext { policy_id: "clusterwide-cr", callback_channel: Some(...), allowed_kubernetes_resources: {} }}: policy_log: validating settings data={}
Error: Policy settings are invalid: Provided settings are not valid: invalid memory settings
all the quantities must be defined
```

```yaml
  settings:
    description: null
    cpu:
      ignoreValues: false
      defaultRequest: 100m
      defaultLimit: 200m
      maxLimit: 300m
    memory:
      ignoreValues: false
      defaultRequest: ''
      defaultLimit: ''
      maxLimit: ''
```

**Comment by jvanz** [comment]
As far as I can see the settings validation is doing the expected. You cannot have empty values when the `ignoreValues` field is `false`. In this case, if the user does not want to validate the `memory` resources, the field in the settings should be empty. I'll take a look in the questions.yaml file to see if there is a way to do that considering the latest settings added, `ignoreValues`.

**Comment by jvanz** [comment]
@jordojordo if I add a checkbox to enable/disable memory or/and cpu settings, the settings sent to the policy will be empty?

For example, if I have a checkbox that enable/disable the questions for the memory settings and the questions for the memory settings will show up only then the checkbox is true (`show_if property). When the user is creating the policy and the checkbox is disabled, will the UI still send the questions the depend in the checkbox value be `true`?
